# Generated by Django 6.0.6 on 2026-06-13 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("movies", "0003_alter_actor_options_alter_director_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("rows", models.PositiveSmallIntegerField()),
                ("seats_per_row", models.PositiveSmallIntegerField()),
            ],
            options={
                "db_table": "halls",
            },
        ),
        migrations.CreateModel(
            name="Screening",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField(blank=True, editable=False)),
                (
                    "hall",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="screenings",
                        to="screenings.hall",
                    ),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="screenings",
                        to="movies.movie",
                    ),
                ),
            ],
            options={
                "db_table": "screenings",
                "ordering": ["start_time"],
            },
        ),
        migrations.CreateModel(
            name="Seat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row", models.PositiveSmallIntegerField()),
                ("number", models.PositiveSmallIntegerField()),
                (
                    "hall",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seats",
                        to="screenings.hall",
                    ),
                ),
            ],
            options={
                "db_table": "seats",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("hall", "row", "number"), name="unique_seat_per_hall"
                    )
                ],
            },
        ),
    ]
