# Generated by Django 6.0.6 on 2026-06-13 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("movies", "0003_alter_actor_options_alter_director_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Screening",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField(blank=True, editable=False)),
                (
                    "hall",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Sala 1"),
                            (2, "Sala 2"),
                            (3, "Sala 3"),
                            (4, "Sala 4"),
                            (5, "Sala 5"),
                        ],
                        default=1,
                    ),
                ),
                ("total_seats", models.PositiveIntegerField()),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="screenings",
                        to="movies.movie",
                    ),
                ),
            ],
            options={
                "db_table": "screenings",
                "ordering": ["start_time"],
            },
        ),
    ]
