# Generated by Django 6.0.6 on 2026-06-13 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screenings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "db_table": "halls",
            },
        ),
        migrations.RemoveField(
            model_name="screening",
            name="total_seats",
        ),
        migrations.AlterField(
            model_name="screening",
            name="hall",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="screenings",
                to="screenings.hall",
            ),
        ),
        migrations.CreateModel(
            name="Seat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row", models.PositiveSmallIntegerField()),
                ("number", models.PositiveSmallIntegerField()),
                (
                    "hall",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seats",
                        to="screenings.hall",
                    ),
                ),
            ],
            options={
                "db_table": "seats",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("hall", "row", "number"), name="unique_seat_per_hall"
                    )
                ],
            },
        ),
    ]
