# Generated by Django 6.0.6 on 2026-06-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screenings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="screening",
            name="price",
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=6),
        ),
    ]
