# Generated by Django 6.0.6 on 2026-06-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0001_initial"),
        ("screenings", "0002_screening_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservationseat",
            options={"ordering": ["reservation"]},
        ),
        migrations.AddField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Oczekująca"),
                    ("confirmed", "Potwierdzona"),
                    ("cancelled", "Anulowana"),
                ],
                default="confirmed",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="reservationseat",
            constraint=models.UniqueConstraint(
                fields=("reservation", "seat"), name="unique_seat_per_reservation"
            ),
        ),
    ]
