# Generated by Django 6.0.6 on 2026-06-15 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reservations",
            "0002_alter_reservationseat_options_reservation_status_and_more",
        ),
        ("screenings", "0002_screening_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="screening",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="screenings.screening",
            ),
        ),
    ]
