# Generated by Django 6.0.6 on 2026-06-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="poster",
            field=models.ImageField(blank=True, null=True, upload_to="posters/"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="trailer_url",
            field=models.URLField(blank=True),
        ),
    ]
