# Generated by Django 6.0.6 on 2026-06-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0002_alter_movie_poster_alter_movie_trailer_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="actor",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="director",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="movie",
            options={"ordering": ["title"]},
        ),
        migrations.AlterModelOptions(
            name="movieactor",
            options={"ordering": ["billing_order"]},
        ),
        migrations.RemoveField(
            model_name="movie",
            name="genre",
        ),
        migrations.AddField(
            model_name="genre",
            name="tmdb_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="genres",
            field=models.ManyToManyField(related_name="movies", to="movies.genre"),
        ),
        migrations.AddField(
            model_name="movie",
            name="vote_average",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=3, null=True
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="vote_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="duration",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="release_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="trailer_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="movieactor",
            name="role_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name="movieactor",
            index=models.Index(fields=["movie"], name="movies_acto_movie_i_6d09eb_idx"),
        ),
        migrations.AddIndex(
            model_name="movieactor",
            index=models.Index(fields=["actor"], name="movies_acto_actor_i_510d90_idx"),
        ),
        migrations.AddConstraint(
            model_name="movieactor",
            constraint=models.UniqueConstraint(
                fields=("movie", "actor"), name="unique_movie_actor"
            ),
        ),
    ]
