# Generated by Django 6.0.6 on 2026-06-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0003_alter_actor_options_alter_director_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="actor",
            name="photo_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="director",
            name="photo_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="poster_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
